version: "{build}"

platform:
  - x86
  - x64

image: Visual Studio 2019

environment:
  GH_TOKEN:
    secure: 3wmca8TBqZGYD33XwQ+hNbS1WJdqkZipCpk3/7EkTtF9F/xhTlpCgM43ofkfie0B

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

# Only build if commit message contains '[build]'
only_commits:
  message: /\[build\]/

install:
  - set /p NODE_VERSION=<.nvmrc
  - ps: Install-Product node $env:NODE_VERSION $env:PLATFORM
  - npm install npm -g
  - npm install electron-builder@next -g
  - npm install --production
  - npm prune

build_script:
  - node --version
  - npm --version
  - npm run winbuild

# Post-install test scripts.
# test_script:
#   - script\test.cmd
test: off