version: "{build}"

platform:
  - x86
  - x64

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

# Only build if commit message contains '[build]'
only_commits:
  message: /\[build\]/

install:
  - set /p NODE_VERSION=<.node-version
  - ps: Install-Product node $env:NODE_VERSION $env:PLATFORM
  - git reset --hard HEAD
  - npm install npm -g

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - script\build.cmd

# Post-install test scripts.
# test_script:
#   - script\test.cmd
test: off